/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg0413_gui;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import javax.swing.JOptionPane;

/**
 *
 * @author User1
 */
public class Ablak extends javax.swing.JFrame {

    /**
     * Creates new form Ablak
     */
    public Ablak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jHirlevel = new javax.swing.JCheckBox();
        jSzakok = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jBeolvas = new javax.swing.JMenu();
        jMentes = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hírlevél");
        setName(""); // NOI18N

        jHirlevel.setText("Kérem a hírlevelet");
        jHirlevel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHirlevelMouseClicked(evt);
            }
        });

        jSzakok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Szakok", "Szoftverfejlesztő", "Rendszerüzemeltető", "Grafikus" }));
        jSzakok.setToolTipText("Szakok");
        jSzakok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSzakokActionPerformed(evt);
            }
        });

        jLabel1.setText("Melyik szakról kér hírlevelet?");

        jBeolvas.setText("Menü");

        jMentes.setText("Mentés(kiír)");
        jMentes.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMentesMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMentesMouseClicked(evt);
            }
        });
        jMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMentesActionPerformed(evt);
            }
        });
        jBeolvas.add(jMentes);

        jMenuItem2.setText("Beolvas");
        jBeolvas.add(jMenuItem2);

        jMenuBar1.add(jBeolvas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jHirlevel)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSzakok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jSzakok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jHirlevel)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSzakokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSzakokActionPerformed
        // TODO add your handling code here:
        System.out.println("kattintott");

    }//GEN-LAST:event_jSzakokActionPerformed

    private void jMentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMentesMouseClicked
        // TODO add your handling code here:
        System.out.println("mentett");
    }//GEN-LAST:event_jMentesMouseClicked

    private void jHirlevelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHirlevelMouseClicked
        // TODO add your handling code here:
        System.out.println("kért");
    }//GEN-LAST:event_jHirlevelMouseClicked

    private void jMentesMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMentesMenuKeyPressed
        // TODO add your handling code here:
                System.out.println("mentett");

    }//GEN-LAST:event_jMentesMenuKeyPressed

    private void jMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMentesActionPerformed
     
//       try{
//       Ment();
//           JOptionPane.showMessageDialog(this, "Sikeres mentés");
//       }catch(IOException ex){
//                  JOptionPane.showMessageDialog(this, "Hiba");
//
//       }
try{
String valasztottSzak=jSzakok.getSelectedItem().toString();
boolean hirleveletkert=jHirlevel.isSelected();
String kert="Kért hírlevelet";
String nemkert="Nem kért hírlevelet";
        if (jHirlevel.isSelected()==true) {
            System.out.println(kert);
        }else{
            System.out.println(nemkert);
        }
         Files.write(Paths.get("mentes.txt"),valasztottSzak.getBytes());
}
catch(IOException ex){

    }
//
//try{
//       String hirleveletkert=jHirlevel.getSelectedIcon().toString();
//
//
//        if (jHirlevel.isSelected()==true) {
//            System.out.println("Kért hírlevelet");
//        }else{
//            System.out.println("Nem kért hírlevelet");
//        }
//         Files.write(Paths.get("mentes.txt"),hirleveletkert.getBytes());
//}
//catch(IOException ex){
//
//    }


      
    }//GEN-LAST:event_jMentesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jBeolvas;
    private javax.swing.JCheckBox jHirlevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMentes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JComboBox<String> jSzakok;
    // End of variables declaration//GEN-END:variables
//private void Ment() throws IOException{
//StringBuilder sb = new StringBuilder();
//sb.append("Választott szak: " + jSzakok.getSelectedItem());
//boolean hirlevel = jHirlevel.isSelected();
//    if (hirlevel==true) {
//        sb.append("\nKért hírlevelet?"+"igen");
//    }else{
//            sb.append("\nKért hírlevelet?"+"nem");
//
//    }
//Files.write(Paths.get("mentes.txt"), sb.toString().getBytes());
//
//        }

}